name: Node CI

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: npm install
        run: 
          make install
      - name: Run linter
        run: 
          make lint
      - name: Run test
        run: 
          make test
      - name: Test & publish test coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true